name: Rust CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.81.0", stable, beta, nightly]
        features: ["", "std", "color_quant", "std,color_quant"]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy
    - name: build
      run: >
        cargo build --verbose --no-default-features --features "${{ matrix.features }}"
    - name: clippy
      run: >
        cargo clippy --verbose --all-targets --no-default-features --features "${{ matrix.features }}"
      if: ${{ matrix.rust == 'stable' }}
    - name: test
      run: >
        cargo test --no-default-features --features "std,${{ matrix.features }}"
      if: ${{ matrix.rust != '1.81.0' }}
  no_std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv7m-none-eabi
    - name: build no_std
      run: >
        cargo build --target thumbv7m-none-eabi
  rustfmt:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Run rustfmt check
      run: cargo fmt -- --check
